### ISSUE TITLE
Projections not working for me with highstock 5.0.12

### ISSUE THREAD

**Issue by marianopeck** [blacklabel/projections#1]
Hi, 

I am trying to use  this plugin with highstock 5.0.12 but I keep getting an error with some charts. Note that in my application I may run a "report" which includes MANY type of charts. Some may have Z axis while others may not, and some would enable projections (only those with Z axis and 3d enabled).

I have this [jsfiddle](url) with the error. 

Any ideas how can I avoid it?

**Comment by Izothep** [comment]
Hi @marianopeck! 

Thank you for reporting your issue. Could you please send us minimal working example of your issue? Unfortunately, your current jsfiddle link is broken.

I look forward to your response.

**Comment by marianopeck** [comment]
Hi @Izothep  

Sorry...I guess the copy paste of the link went wrong. [ Here it is ](http://jsfiddle.net/57bcnpo8/).
I am sure the problem  is something obvious....

Thanks!

**Comment by Izothep** [comment]
@marianopeck thank you for providing us with working jsFiddle example.


It looks that your issue is fixed by https://github.com/blacklabel/projections/commit/4e40d3a80afdd3a0b76c871979c900c5b02c0e5c

Please let me know if you have any further questions related to this issue.

**Comment by marianopeck** [comment]
Thanks to you @Izothep 
That indeed fixed it. Thanks for your quick support. Already enjoying the plugin now.
