### ISSUE TITLE
Is there a way to stop auto enabling of plane projections?

### ISSUE THREAD

**Issue by marianopeck** [blacklabel/projections#2]
Hi,

I found that sometimes, for some charts, plane projections are automatically added even if I haven't explicitly set it. I found that a bit disturbing as I must explicitly disable it for the cases I don't want it. I would prefer to explicitly enabled when needed. Even more confusing is that only plane projections are enable by line are not. 

See this [jsfiddle](http://jsfiddle.net/jy4xwhcu/) as an example. 

Is there a way I can globally disable plane projections unless explicitly enabled?

Thanks  in advance,

**Comment by Izothep** [comment]
Hi @marianopeck!

Thank you for your message. 

In our Projections plugin plane projections are enabled by default and line projections are disabled by default. You can simply override this options by using Highcharts.setOptions method:
http://api.highcharts.com/highcharts/Highcharts.setOptions

I have prepared very simple example of using Highcharts.setOptions for disabling plane projections in chart. You can find this example in the link below:
http://jsfiddle.net/jy4xwhcu/1/

Please let me know if you have any further questions.

Best,
